sudo: required
language: go

go:
  - 1.13.x

services:
  - docker

script:
- make test
- make verify-codegen
- TAG=${TRAVIS_TAG:=latest} make build

before_deploy:
- echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  provider: script
  script: TAG=${TRAVIS_TAG} make push manifest
  on:
    tags: true

env:
- GO111MODULE=on
