apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: functioningresses.openfaas.com
spec:
  group: openfaas.com
  version: v1alpha2
  versions:
    - name: v1alpha2
      served: true
      storage: true
  names:
    singular: functioningress
    plural: functioningresses
    kind: FunctionIngress
    shortNames:
    - fni
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - domain
          properties:
            name:
              type: string
              pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
            domain:
              type: string
            tls:
              type: boolean
            issuerRef:
              type: string
            issuerType:
              type: string
            ingressType:
              type: string
