apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: functioningresses.openfaas.com
spec:
  group: openfaas.com
  version: v1alpha2
  versions:
    - name: v1alpha2
      served: true
      storage: true
  names:
    singular: functioningress
    plural: functioningresses
    kind: FunctionIngress
    shortNames:
    - fni
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Domain
    type: string
    JSONPath: .spec.domain
  - name: Function
    type: string
    JSONPath: .spec.function
  - name: IngressType
    type: string
    JSONPath: .spec.ingressType
  - name: TLS
    type: boolean
    JSONPath: .spec.tls.enabled
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - domain
          properties:
            name:
              type: string
              pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
            domain:
              type: string
            ingressType:
              type: string
            tls:
              type: object
              properties:
                enabled:
                  type: boolean
                issuerRef:
                  type: object
                  anyOf:
                    - type: string
                    - type: object
                  required: ['kind', 'name']
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
    